version: "3.9"
services:
  archive-server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./.env:/go/src/.env:Z
  mongo-groupme:
    image: "mongo"
    #    ports:
    #      - "27017:27017"
    volumes:
      - ~/groupme-data:/data/db:Z
